---
name: Gonzalo
surname: García-Castro
position: "Investigador predoctoral"
address: "Ramon Trias Fargas 25, 08005 Barcelona"
phone: 
profilepic: 
www: gongcastro.github.io
email: "gonzalo.garciadecastro@upf.edu"
twitter: gongcastro
github: gongcastro
linkedin: gongcastro
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Investigador en psicolingüística, científico de datos y programador de R"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)

```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Grado en Psicología", "2013-2017", "Universidad de Oviedo", "Oviedo",
  "Master en Neurociencia", "2017-2018", "Universitat de Barcelona", "Barcelona",
  "Doctorando en Biomedicina", "2018-actualmente", "Universitat Pompeu Fabra", "Barcelona"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

